version: 2
registries:
  maven-virtual:
    type: maven-repository
    url: https://jaisri.jfrog.io/artifactory/default-maven-virtual/
    username: jaisri306@gmail.com
    password: Jaisri@888
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:"*"
    schedule:
      interval: "daily"
    
