version: 2
registries:
  docker-virtual:
    type: docker-registry
    url: https://jaisri.jfrog.io/artifactory/default-docker-virtual/
    username: jaisri306@gmail.com
    password: Jaisri@888
updates:
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    
